[tools]
atuin = { version = "latest", os = ["windows", "linux"] }
bat = { version = "latest", os = ["windows", "linux"] }
bob = { version = "latest", os = ["windows", "linux"] }
"cargo:pay-respects" = { version = "latest", os = ["windows", "linux"] }
"cargo:pay-respects-module-request-ai" = { version = "latest", os = ["windows", "linux"] }
"cargo:pay-respects-module-runtime-rules" = { version = "latest", os = ["windows", "linux"] }
"cargo:procs" = { version = "latest", os = ["windows", "linux"] }
chezmoi = { version = "latest", os = ["windows", "linux"] }
cmake = { version = "latest", os = ["windows", "linux"] }
delta = { version = "latest", os = ["windows", "linux"] }
dust = { version = "latest", os = ["windows", "linux"] }
eza = { version = "latest", os = ["windows", "linux"] }
fastfetch = { version = "latest", os = ["windows", "linux"] }
fd = { version = "latest", os = ["windows", "linux"] }
fzf = { version = "latest", os = ["windows", "linux"] }
go = { version = "latest", os = ["windows", "linux"] }
"go:github.com/hickford/git-credential-oauth" = { version = "latest", os = ["linux"] }
hugo = { version = "latest", os = ["windows"] }
jj = { version = "latest", os = ["windows", "linux"] }
make = { version = "latest", os = ["linux"] }
meson = { version = "latest", os = ["linux"] }
ninja = { version = "latest", os = ["windows", "linux"] }
node = { version = "latest", os = ["windows", "linux"] }
pi = { version = "latest", os = ["windows", "linux"] }
python = { version = "latest", os = ["windows", "linux"] }
ripgrep = { version = "latest", os = ["windows", "linux"] }
rust = { version = "latest", os = ["windows", "linux"] }
starship = { version = "latest", os = ["windows", "linux"] }
tree-sitter = { version = "0.25", os = ["windows", "linux"] }
usage = { version = "latest", os = ["windows", "linux"] }
uv = { version = "latest", os = ["windows", "linux"] }
zellij = { version = "latest", os = ["windows", "linux"] }
zoxide = { version = "latest", os = ["windows", "linux"] }

[env]
MISE_BACKENDS_BOB = "cargo:bob-nvim"
MISE_BACKENDS_PI = "npm:@mariozechner/pi-coding-agent"
MISE_BACKENDS_ZELLIJ = "cargo:zellij"

[settings]
experimental = true
