[tools]
atuin = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
go = "latest"
"go:github.com/hickford/git-credential-oauth" = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
tree-sitter = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
experimental = true
