[tools]
atuin = { version = "latest", os = ["linux"] }
bat = { version = "latest", os = ["windows", "linux"] }
chezmoi = { version = "latest", os = ["windows", "linux"] }
clangd = { version = "latest", os = ["windows", "linux"] }
delta = { version = "latest", os = ["windows", "linux"] }
dust = { version = "latest", os = ["windows", "linux"] }
eza = { version = "latest", os = ["windows", "linux"] }
fastfetch = { version = "latest", os = ["windows", "linux"] }
fzf = { version = "latest", os = ["windows", "linux"] }
go = { version = "latest", os = ["windows", "linux"] }
"go:github.com/hickford/git-credential-oauth" = { version = "latest", os = ["linux"] }
"go:golang.org/x/tools/gopls" = { version = "latest", os = ["windows", "linux"] }
"go:oss.terrastruct.com/d2" = { version = "latest", os = ["windows"] }
hugo = { version = "latest", os = ["windows"] }
neovim = { version = "latest", os = ["windows", "linux"] }
node = { version = "latest", os = ["windows", "linux"] }
"npm:@microsoft/compose-language-service" = { version = "latest", os = ["windows", "linux"] }
"npm:dockerfile-language-server-nodejs" = { version = "latest", os = ["windows", "linux"] }
python = { version = "latest", os = ["windows", "linux"] }
ripgrep = { version = "latest", os = ["windows", "linux"] }
rust = { version = "latest", os = ["windows", "linux"] }
tree-sitter = { version = "latest", os = ["windows", "linux"] }
zellij = { version = "latest", os = ["linux"] }
zoxide = { version = "latest", os = ["windows", "linux"] }

[settings]
experimental = true
